### ISSUE TITLE
Pre-presentation review

### ISSUE THREAD

**Issue by lele0007** [lele0007/Blood-vessel-segmentation#2]
@smiths Hi Prof. Smiths, I have uploaded my presentation PPT, please review it.
     [SRS presentation](https://github.com/lele0007/Blood-vessel-segmentation/blob/main/docs/Presentations/SRS_Presentation.pdf)

**Comment by smiths** [comment]
Feedback:

- too many slides - you only have 15 minutes - you should aim for half as many slides
- you don't need all the text on slide 3 - you can just have the two pictures and explain them to the audience
- you don't need the why slide, you can say that over the previous picture
- you shouldn't make any slides based on the following observation, but when you make your SRS, be sure to separate the machine learning parts from the problem definition.  ML is not the only way to solve this problem.  (Conventional image segmentation is also an option.)  You want your document to support potential future change.
- you model is all about the ML algorithm, what about the original problem?  You should represent what a segmentation is.  What is the type of an image?  What is the type of the output?  I had a student work on fMRI in the past.  Here [SRS](https://gitlab.cas.mcmaster.ca/SEforSC/se4sc/-/blob/git-svn/GradStudents/Mojdeh/SRS_3dfim+/3dfim+.pdf) might be helpful for you.
- You need to decompose your model into separate theoretical models.  That is how theory is represented in the SRS template.  For each theory think about the input and the output.
- I have a suspicion that you can be more abstract in how you present your ML algorithm.  The details can wait until the design.
- I like your accuracy slide.  Your definition of ACC should be a theoretical model.
- Another measure of accuracy that might help is the [dice coefficient](https://www.kaggle.com/code/yerramvarun/understanding-dice-coefficient)
