### ISSUE TITLE
Review MG and MIS document

### ISSUE THREAD

**Issue by lele0007** [lele0007/Blood-vessel-segmentation#20]
@smiths  please review my MG and MIS document.

[MG ](https://github.com/lele0007/Blood-vessel-segmentation/blob/main/docs/Design/SoftArchitecture/MG.pdf)
[MIS](https://github.com/lele0007/Blood-vessel-segmentation/blob/main/docs/Design/SoftDetailedDes/MIS.pdf)

**Comment by smiths** [comment]
[XinyuMG.pdf - PDF Expert.pdf](https://github.com/lele0007/Blood-vessel-segmentation/files/1484
[XinyuMIS.pdf - PDF Expert.pdf](https://github.com/lele0007/Blood-vessel-segmentation/files/14846230/XinyuMIS.pdf.-.PDF.Expert.pdf)
6229/XinyuMG.pdf.-.PDF.Expert.pdf)
