### ISSUE TITLE
Review MG and MIS document (Domain Expert)

### ISSUE THREAD

**Issue by lele0007** [lele0007/Blood-vessel-segmentation#21]
@gordonwky please review my MG and MIS document.

[MG](https://github.com/lele0007/Blood-vessel-segmentation/blob/main/docs/Design/SoftArchitecture/MG.pdf)
[MIS](https://github.com/lele0007/Blood-vessel-segmentation/blob/main/docs/Design/SoftDetailedDes/MIS.pdf)

**Comment by gordonwky** [comment]
My review is here.
[MG-Xinyu.pdf](https://github.com/lele0007/Blood-vessel-segmentation/files/14680723/MG-Xinyu.pdf)
[MIS-Xinyu.pdf](https://github.com/lele0007/Blood-vessel-segmentation/files/14680724/MIS-Xinyu.pdf)
