### ISSUE TITLE
Review MG and MISdocument (Secondary Reviewer)

### ISSUE THREAD

**Issue by lele0007** [lele0007/Blood-vessel-segmentation#22]
@alimousavi1997 please review my MG and MIS document.

[MG](https://github.com/lele0007/Blood-vessel-segmentation/blob/main/docs/Design/SoftArchitecture/MG.pdf)
[MIS](https://github.com/lele0007/Blood-vessel-segmentation/blob/main/docs/Design/SoftDetailedDes/MIS.pdf)

**Comment by alimousavi1997** [comment]
Hello. I have attached some feedback.  Overall your documents are well-written.
[MIS_reviewed.pdf](https://github.com/lele0007/Blood-vessel-segmentation/files/14812551/MIS_reviewed.pdf)
[MG_reviewed.pdf](https://github.com/lele0007/Blood-vessel-segmentation/files/14812553/MG_reviewed.pdf)
