### ISSUE TITLE
Review VnV Plan document 

### ISSUE THREAD

**Issue by lele0007** [lele0007/Blood-vessel-segmentation#7]
@smiths please review my VnV Plan document.
[VnV Plan](https://github.com/lele0007/Blood-vessel-segmentation/blob/main/docs/VnVPlan/vnv.pdf)

**Comment by smiths** [comment]
[Xinyu_main.pdf](https://github.com/lele0007/Blood-vessel-segmentation/files/14566814/Xinyu_main.pdf)
